### PR TITLE
Empty data structures, handle non-numerics consistently, and typed-array support.

### PR DESCRIPTION
**Pull request by kgryte**

### CODE REVIEW

**Comment by Planeshifter** [comment]
No comments regarding the code, but we should be aware of some strange outputs that can happen for arrays, e.g.

1) 

```
var arr = [ {'x': null} ]

erfc( arr, {'accessor': getValue } )
// returns [ 1 ] 

function getValue( d ) {
    return d.x;
}
```

We need to handle `null` as an input somehow, that the number one gets returned is misleading.

2) 

```
var arr = [ {'x': 1.2} ]

erfc( arr  )
// returns [ 0 ] 
```

Should we re-evaluate the decision to not check for numeric values? Or provide a `strict` option which ensures that only the correct types are entered?

**Comment by Planeshifter** [comment]
Looks all good to me. Publish?

**Comment by kgryte** [comment]
Not yet. I am thinking that `typed-arrays` should be handled separately. Right now, because `typed-arrays` are funneled to the `arrays` implementation, each value is typed checked. But this check is pointless for `typed-arrays`. I am thinking for other modules where no distinction is made between plain and typed `arrays`, the `typedarray.js` file simply imports the `array.js` file. Your thoughts?

**Comment by kgryte** [comment]
Module is ready for review.

**Comment by Planeshifter** [comment]
LGTM. Publish?

**Comment by kgryte** [comment]
@Planeshifter While only typos were fixed, probably worthwhile to have another quick pass through in case I have forgotten any thing in terms of current thinking, etc.

**Comment by Planeshifter** [comment]
Only made some minor edits, should be ready to land on npm.

**Comment by kgryte** [comment]
Awesome. Thanks!

**Pull request merged**
